baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "PhDaddy"
theme = "hugo-strata-theme"
disqusShortname = "phdaddy"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "David Rohrer"
	description = "Describe your website"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "A site of mediocre blog posts<br> and poorly edited videos!"
		# The icons will be shown if you enter your username
		twitter = "thephdaddy"
		github = ""
		dribbble = ""
		facebook = "thephdaddy"
		googleplus = "thephdaddy"
		flickr = ""
		linkedin = ""
		youtube = "channel/UCZ_Fb-2C4JDIAhz1LY6TSFg"

		copyright = [
			"&copy; David Rohrer",
			"Design: [HTML5 UP](//html5up.net)",
			"Hugo Theme: [digitalcraftsman] (https://github.com/digitalcraftsman)"
		]


	[params.about]
		hide  = false
		title = "Welcome to PhDaddy.com!"
		content = "You have (probably accidentally) stumbled onto my site of mediocre blog posts and poorly edited videos! I don't recommend that you stay here long, but if you do, you may see content related to parenting and general family life (and you will definitely be worse off for viewing it)."

	[params.aboutBlog]
		hide  = false
		title = "The PhDaddy Blog"
		content = "Here are all the blog posts I have ever written. I would like to say the newer ones are better, but they are all pretty bad. One day I might organize them better, but for now good luck finding something interesting..."
		
	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = true
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = ""

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 11
	
[[menu.main]]
	name = "About"
	url  = "about/"
	weight = 12